refactored. issue #7

diff --git a/usr/sbin/firewall-tester b/usr/sbin/firewall-tester
--- a/usr/sbin/firewall-tester
+++ b/usr/sbin/firewall-tester
@@ -2,7 +2,6 @@
 
 # svirepunchik@gmail.com (c) 2018
 # firewall test script
-# dependencies: nmap, tee, awk, sed, grep
 
 OPTS=`getopt -o hs:a:l:b --long help,server:,allowed:,logfile:,batch -n 'parse-options' -- "$@"`
 
@@ -11,15 +10,17 @@ if [ $? != 0 ] ; then echo "Failed parsing options." >&2 ; exit 1 ; fi
 usage="$(basename "$0") [-h] [-s server_name|server_ip] [-a \"allowed_port1, allowed_port2, ..., allowed_port n\"] [-l /path/to/log.file] [-b]
 this script scans all the server ports
 where:
-    -h | --help     show this help text
-    -s | --server   set server name or server ip (default is 127.0.0.1)
-    -a | --allowed  set allowed ports in  (default is 22,80,443)
-    -l | --logfile  set log file location (default is /var/log/firewall.scan.log)
-    -b | --batch    set batch mode, script will use server.list and will ignore -s and -a options"
+    -h | --help                     show this help text
+    -s | --server   <fqdn|ip>       set target server name or IP (default is 127.0.0.1)
+    -a | --allowed  \"port1,port2\" set allowed ports in  (default is \"22, 80, 443\")
+    -l | --logfile  /path/to/log    set log file location (default is /var/log/firewall.scan.log)
+    -b | --batch                    set batch mode, script will use server.list and will ignore -s and -a options"
 
 server="127.0.0.1"
 allowed="22,80,443"
 logfile="/var/log/firewall.scan.log"
+etcdir="/etc/firewall-tester"
+hookdir="/usr/lib/firewall-tester"
 
 nmapbin=`which nmap`
 if [[ $? != 0 ]]; then echo "NMAP is not found. Please install NMAP."; exit 1; fi
@@ -52,69 +53,65 @@ if [[ ! -e $logfile ]]; then touch $logfile; fi
 if [[ ! -w $logfile || $? -ne 0 ]]; then echo "log file $logfile is not writeable or cant create log file!"; exit 1; fi
 
 function check_server () {
-    if [[ -z "$1" ]]; then echo "server not found" exit; else SERVER=$1; fi
-    if [[ -z "$2" ]]; then ALLOWED="none"; else ALLOWED=$2; fi
+    local allowed
+    local server
+    local nmaptmp
+    local allowedgrep
 
-    echo $(date +"%Y.%m.%d %H:%M:%S") - scanning server $SERVER. allowed ports: $ALLOWED | $teebin -a $logfile
-    NMAPTMP=`mktemp`
+    if [[ -z "$1" ]]; then echo "server not found" exit; else server=$1; fi
+    if [[ -z "$2" ]]; then allowed="none"; else allowed=$2; fi
+
+    echo $(date +"%Y.%m.%d %H:%M:%S") - scanning server $server. allowed ports: $allowed | $teebin -a $logfile
+    nmaptmp=`mktemp`
     if [[ $? -ne 0 ]]; then echo "cant create temp file."; exit 1; fi
-    $nmapbin -r -v0 -p 1-65535 --max-retries 1 -n $SERVER -oN $NMAPTMP > /dev/null
+    $nmapbin -r -v0 -p 1-65535 --max-retries 1 -n $server -oN $nmaptmp > /dev/null
 
-    ALLOWEDGREP=`echo $ALLOWED | $sedbin -e 's/ *, */\\\|/g'`
-    OPENPORTS=`$grepbin -e '.*open.[^port]' $NMAPTMP | $grepbin -v "$ALLOWEDGREP"`
+    allowedgrep=`echo $allowed | $sedbin -e 's/ *, */\\\|/g'`
+    openports=`$grepbin -e '.*open.[^port]' $nmaptmp | $grepbin -v "$allowedgrep"`
 
-    rm -rf $NMAPTMP
+    rm -rf $nmaptmp
 
-    if [[ -n "$OPENPORTS" ]]; then
+    if [[ -n "$openports" ]]; then
         echo $(date +"%Y.%m.%d %H:%M:%S") - YOUR SERVER IS NOT SECURE | $teebin -a $logfile
         echo $(date +"%Y.%m.%d %H:%M:%S") - found open ports: | $teebin -a $logfile
         echo -e "PORT\tSTATE\tSERVICE\tREASON" | $teebin -a $logfile
-        echo "$OPENPORTS" | $teebin -a $logfile
+        echo "$openports" | $teebin -a $logfile
         return 1
     else
-        echo $(date +"%Y.%m.%d %H:%M:%S") - server $SERVER has no unnesessary open ports | $teebin -a $logfile
+        echo $(date +"%Y.%m.%d %H:%M:%S") - server $server has no unnesessary open ports | $teebin -a $logfile
         return 0
     fi
 }
 
-SOURCE="${BASH_SOURCE[0]}"
-while [ -h "$SOURCE" ]; do
-  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
-  SOURCE="$(readlink "$SOURCE")"
-  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
-done
-OPTDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
-if [[ -f /etc/firewall.tester/server.list ]]; then ETCDIR="/etc/firewall.tester"; else ECTDIR=$OPTDIR; fi
-
 if [[ $batch ]]
 then
-    if [[ ! -e $ETCDIR/server.list ]]; then echo $(date +"%Y.%m.%d %H:%M:%S") - $ETCDIR/server.list is not found. aborting | $teebin -a $logfile; exit 1; fi
+    if [[ ! -e $etcdir/server.list ]]; then echo $(date +"%Y.%m.%d %H:%M:%S") - $etcdir/server.list is not found. aborting | $teebin -a $logfile; exit 1; fi
     flag=0
-    while read -r LINE; do
-        if [[ "$LINE" =~ ^#.*$ ]]; then continue; fi
-        if [[ -z "$LINE" ]]; then continue; fi
-        declare $( echo $LINE | $awkbin '{print "bserver="$1; print "ballowed="$2;}' )
-        check_server $bserver $ballowed
+    while read -r line; do
+        if [[ "$line" =~ ^#.*$ ]]; then continue; fi
+        if [[ -z "$line" ]]; then continue; fi
+        declare $( echo $line | $awkbin '{print "server="$1; print "allowed="$2;}' )
+        check_server $server $allowed
         if [[ $? != 0 ]]; then
             flag=1;
-            if [[ -e $OPTDIR/hook.server.sh ]]; then
+            if [[ -e $hookdir/hook.server.sh ]]; then
                 echo $(date +"%Y.%m.%d %H:%M:%S") - calling per server hook | $teebin -a $logfile
-                $OPTDIR/hook.server.sh "$bserver" "$ballowed" "$OPENPORTS"
+                $hookdir/hook-server.sh "$server" "$allowed" "$openports"
             fi
         fi
-    done < $ETCDIR/server.list
+    done < etcdir/server.list
     if [[ $flag -eq 1 ]]; then
-        if [[ -e $OPTDIR/hook.all.sh ]]; then
+        if [[ -e $hookdir/hook.all.sh ]]; then
             echo $(date +"%Y.%m.%d %H:%M:%S") - calling common hook | $teebin -a $logfile
-            $OPTDIR/hook.all.sh
+            $hookdir/hook-all.sh
         fi
     fi
 else
     check_server $server $allowed
     if [[ $? != 0 ]]; then
-        if [[ -e $OPTDIR/hook.server.sh ]]; then
+        if [[ -e $hookdir/hook-server.sh ]]; then
             echo $(date +"%Y.%m.%d %H:%M:%S") - calling per server hook | $teebin -a $logfile
-            $OPTDIR/hook.server.sh "$server" "$allowed" "$OPENPORTS"
+            $hookdir/hook.server.sh "$server" "$allowed" "$openports"
         fi
     fi
 fi
